### ISSUE TITLE
@istikradendoit  Thanks for the response, attached detailed document.

### ISSUE THREAD

**Issue by kishorev6** [endoit/vscode-siebelscriptseditor#2] opened 2022-06-07 13:45 UTC
@istikradendoit  Thanks for the response, attached detailed document.

Thanks,
Venkat
[Script editor.docx](https://github.com/endoit/vscode-siebelscriptseditor/files/8853613/Script.editor.docx)

_Originally posted by @kishorev6 in https://github.com/endoit/vscode-siebelscriptseditor/issues/1#issuecomment-1148685724_

**Comment by lbakosendo** [comment] 2022-06-07 13:58
Hi,

Yes, the problem may be caused by having a 32-bit client as well. We encountered similar problems when both clients were installed. In that case a working solution was to install the normal 64-bit database client instead of the instant 64-bit client. https://www.oracle.com/database/technologies/oracle19c-windows-downloads.html 

Let me know if it helps.

Thanks,
László

**Comment by kishorev6** [comment] 2022-06-07 14:01
if i install 64 bit i hope it would not effect my existing connections :) any thoughts?

Thanks

**Comment by lbakosendo** [comment] 2022-06-07 14:14
In my case, it did not interfere with any existing connections, and in theory, they can coexist without a problem. However, I can not be sure about your case. Let's hope it does not affect them if you install it.

László

**Comment by kishorev6** [comment] 2022-06-07 14:15
Thanks for the reply installing 64 now will let you know.


Venkat

**Comment by kishorev6** [comment] 2022-06-07 15:01
hi 
![image](https://user-images.githubusercontent.com/106764910/172413877-f6a895ad-229f-428c-8a01-51ef3879c757.png)

**Comment by kishorev6** [comment] 2022-06-07 15:02
this is the one you installed could you please confirm. Thanks

Venkat

**Comment by lbakosendo** [comment] 2022-06-07 15:12
Yes, this is it.



________________________________
Feladó: kishorev6 ***@***.***>
Elküldve: 2022. június 7., kedd 17:02
Címzett: endoit/vscode-siebelscriptseditor ***@***.***>
Másolat: Dr. Bakos László Péter ***@***.***>; Comment ***@***.***>
Tárgy: Re: [endoit/vscode-siebelscriptseditor] @istikradendoit  Thanks for the response, attached detailed document. (Issue #2)


this is the one you installed could you please confirm. Thanks

Venkat

**Comment by kishorev6** [comment] 2022-06-07 17:12
i did install and added tns file on 64bit, but still not able to connect, update path on environment variable as
C:\app1\product\19.0.0\client_1\bin

Venkat

**Comment by kishorev6** [comment] 2022-06-07 20:24
app1 = 64bit
app = 32 bit

![image](https://user-images.githubusercontent.com/106764910/172475595-e67cd642-891b-4cb6-a1a9-aad6d74bda03.png)

**Comment by kishorev6** [comment] 2022-06-07 20:25
![image](https://user-images.githubusercontent.com/106764910/172475784-74c07e9d-7683-497d-a4fb-6cdf1448eb8d.png)

**Comment by kishorev6** [comment] 2022-06-07 21:18
Hi

you posted this "After clicking the "Test database connection" button? That button sends the following query to the database: SELECT ROW_ID, NAME FROM SIEBEL.S_REPOSITORY"

but we are not using "SIEBEL" table owner we use example(ABC_APPS.S_REPOSITORY), so i guess this the problem.
so can we edit the table owner when we click on "Test database connection" button? if so how can we do that.

Venkat

**Comment by lbakosendo** [comment] 2022-06-08 07:36
Hi,

It is not possible currently to change the table owner from SIEBEL to any other. It will be fixed in a future release.

László

**Comment by kishorev6** [comment] 2022-06-08 11:42
Hi,
Thanks for the reply.. so table owner is the issue. is there any space to follow for future releases or you post here?

Venkat

**Comment by lbakosendo** [comment] 2022-06-08 11:53
Hi,

It will be posted here.

László

**Comment by istikradendoit** [comment] 2022-08-09 16:04
Hi, the new version has been released which uses the Siebel REST API, so no more wresting with the database. :) It's now available in the VS Code Extension Marketplace and the source code is also available here: https://github.com/endoit/siebelScriptsEditor.

**Closed as completed by istikradendoit** 2022-08-09 16:04 UTC
